In [ ]:
# Import necessary libraries: pandas for data manipulation and numpy for numerical operations.
import pandas as pd
import numpy as np

In [ ]:
# Load the dataset 'Bengaluru_House_Data.csv' into a pandas DataFrame named 'data'.
data=pd.read_csv('/content/Bengaluru_House_Data.csv')

In [ ]:
# Display the first 5 rows of the DataFrame to get a quick overview of the data.
data.head()

,area_type,availability,location,size,society,total_sqft,bath,balcony,price
0,Super built-up Area,19-Dec,Electronic City Phase II,2 BHK,Coomee,1056,2.0,1.0,39.07
1,Plot Area,Ready To Move,Chikka Tirupathi,4 Bedroom,Theanmp,2600,5.0,3.0,120.00
2,Built-up Area,Ready To Move,Uttarahalli,3 BHK,NaN,1440,2.0,3.0,62.00
3,Super built-up Area,Ready To Move,Lingadheeranahalli,3 BHK,Soiewre,1521,3.0,1.0,95.00
4,Super built-up Area,Ready To Move,Kothanur,2 BHK,NaN,1200,2.0,1.0,51.00

In [ ]:
# Display the number of rows and columns in the DataFrame.
data.shape

(13320, 9)

In [ ]:
# Display a concise summary of the DataFrame, including data types and non-null values.
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13320 entries, 0 to 13319
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   area_type     13320 non-null  object
 1   availability  13320 non-null  object
 2   location      13319 non-null  object
 3   size          13304 non-null  object
 4   society       7818 non-null   object
 5   total_sqft    13320 non-null  object
 6   bath          13247 non-null  float64
 7   balcony       12711 non-null  float64
 8   price         13320 non-null  float64
dtypes: float64(3), object(6)
memory usage: 936.7+ KB

In [ ]:
# Iterate through each column and print the value counts for each unique entry, followed by a separator.
for column in data.columns:
  print(data[column].value_counts())
  print("*"*20)

area_type
Super built-up  Area    8790
Built-up  Area          2418
Plot  Area              2025
Carpet  Area              87
Name: count, dtype: int64
********************
availability
Ready To Move    10581
18-Dec             307
18-May             295
18-Apr             271
18-Aug             200
                 ...
16-Oct               1
17-Jan               1
16-Nov               1
16-Jan               1
14-Jul               1
Name: count, Length: 81, dtype: int64
********************
location
Whitefield                         540
Sarjapur  Road                     399
Electronic City                    302
Kanakpura Road                     273
Thanisandra                        234
                                  ...
3rd Stage Raja Rajeshwari Nagar      1
Chuchangatta Colony                  1
Electronic City Phase 1,             1
Chikbasavanapura                     1
Abshot Layout                        1
Name: count, Length: 1305, dtype: int64
********************
size
2 BHK         5199
3 BHK         4310
4 Bedroom      826
4 BHK          591
3 Bedroom      547
1 BHK          538
2 Bedroom      329
5 Bedroom      297
6 Bedroom      191
1 Bedroom      105
8 Bedroom       84
7 Bedroom       83
5 BHK           59
9 Bedroom       46
6 BHK           30
7 BHK           17
1 RK            13
10 Bedroom      12
9 BHK            8
8 BHK            5
11 BHK           2
10 BHK           2
11 Bedroom       2
27 BHK           1
19 BHK           1
43 Bedroom       1
16 BHK           1
14 BHK           1
12 Bedroom       1
13 BHK           1
18 Bedroom       1
Name: count, dtype: int64
********************
society
GrrvaGr    80
PrarePa    76
Sryalan    59
Prtates    59
GMown E    56
           ..
SLtalry     1
Rencyes     1
DiaveEn     1
Suiumy      1
Amionce     1
Name: count, Length: 2688, dtype: int64
********************
total_sqft
1200           843
1100           221
1500           205
2400           196
600            180
              ...
2920             1
5665.84          1
1369             1
7150             1
1200 - 1470      1
Name: count, Length: 2117, dtype: int64
********************
bath
2.0     6908
3.0     3286
4.0     1226
1.0      788
5.0      524
6.0      273
7.0      102
8.0       64
9.0       43
10.0      13
12.0       7
11.0       3
13.0       3
16.0       2
27.0       1
14.0       1
40.0       1
15.0       1
18.0       1
Name: count, dtype: int64
********************
balcony
2.0    5113
1.0    4897
3.0    1672
0.0    1029
Name: count, dtype: int64
********************
price
75.00    310
65.00    302
55.00    275
60.00    270
45.00    240
        ...
43.04      1
61.11      1
46.56      1
42.54      1
47.35      1
Name: count, Length: 1994, dtype: int64
********************

In [ ]:
# Check for missing values in each column and sum them up.
data.isna().sum()

area_type          0
availability       0
location           1
size              16
society         5502
total_sqft         0
bath              73
balcony          609
price              0
dtype: int64

In [ ]:

# Drop irrelevant columns ('area_type', 'availability', 'society', 'balcony') from the DataFrame.
data.drop(columns=['area_type','availability','society','balcony'], inplace=True)

In [ ]:

# Display descriptive statistics (count, mean, std, min, max, quartiles) for numerical columns.
data.describe()

               bath         price
count  13247.000000  13320.000000
mean       2.692610    112.565627
std        1.341458    148.971674
min        1.000000      8.000000
25%        2.000000     50.000000
50%        2.000000     72.000000
75%        3.000000    120.000000
max       40.000000   3600.000000

In [ ]:
# Display an updated concise summary of the DataFrame after dropping columns.
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13320 entries, 0 to 13319
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   location    13319 non-null  object
 1   size        13304 non-null  object
 2   total_sqft  13320 non-null  object
 3   bath        13247 non-null  float64
 4   price       13320 non-null  float64
dtypes: float64(2), object(3)
memory usage: 520.4+ KB

In [ ]:
# Display the value counts for the 'location' column.
data['location'].value_counts()

location
Whitefield                         540
Sarjapur  Road                     399
Electronic City                    302
Kanakpura Road                     273
Thanisandra                        234
                                  ...
3rd Stage Raja Rajeshwari Nagar      1
Chuchangatta Colony                  1
Electronic City Phase 1,             1
Chikbasavanapura                     1
Abshot Layout                        1
Name: count, Length: 1305, dtype: int64

In [ ]:
# Fill any missing values in the 'location' column with 'Sarjapur Road'.
data['location']= data['location'].fillna('Sarjapur Road')

In [ ]:
# Display the value counts for the 'size' column.
data['size'].value_counts()

size
2 BHK         5199
3 BHK         4310
4 Bedroom      826
4 BHK          591
3 Bedroom      547
1 BHK          538
2 Bedroom      329
5 Bedroom      297
6 Bedroom      191
1 Bedroom      105
8 Bedroom       84
7 Bedroom       83
5 BHK           59
9 Bedroom       46
6 BHK           30
7 BHK           17
1 RK            13
10 Bedroom      12
9 BHK            8
8 BHK            5
11 BHK           2
10 BHK           2
11 Bedroom       2
27 BHK           1
19 BHK           1
43 Bedroom       1
16 BHK           1
14 BHK           1
12 Bedroom       1
13 BHK           1
18 Bedroom       1
Name: count, dtype: int64

In [ ]:
# Fill any missing values in the 'size' column with '2BHK'.
data['size']=data['size'].fillna('2BHK')

In [ ]:
# Fill any missing values in the 'bath' (number of bathrooms) column with the median value of the column.
data['bath']=data['bath'].fillna(data['bath'].median())

In [ ]:
# Display an updated concise summary of the DataFrame after handling missing values.
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13320 entries, 0 to 13319
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   location    13320 non-null  object
 1   size        13320 non-null  object
 2   total_sqft  13320 non-null  object
 3   bath        13320 non-null  float64
 4   price       13320 non-null  float64
dtypes: float64(2), object(3)
memory usage: 520.4+ KB

In [ ]:
# Extract the numerical part from the 'size' column to create a new 'bhk' (BHK - Bedroom, Hall, Kitchen) column, and convert it to integer type.
data['bhk']=data['size'].str.extract('(\d+)').astype(int)

<>:2: SyntaxWarning: invalid escape sequence '\d'
<>:2: SyntaxWarning: invalid escape sequence '\d'
/tmp/ipykernel_618/969694795.py:2: SyntaxWarning: invalid escape sequence '\d'
  data['bhk']=data['size'].str.extract('(\d+)').astype(int)

In [ ]:
# Display rows where the 'bhk' count is unusually high (greater than 20) to identify potential data entry errors or outliers.
data[data.bhk > 20]

                       location        size total_sqft  bath  price  bhk
1718  2Electronic City Phase II      27 BHK       8000  27.0  230.0   27
4684                Munnekollal  43 Bedroom       2400  40.0  660.0   43

In [ ]:
# Display all unique values in the 'total_sqft' column to understand its data format.
data['total_sqft'].unique()

array(['1056', '2600', '1440', ..., '1133 - 1384', '774', '4689'],
      dtype=object)

In [ ]:
# Define a function to convert 'total_sqft' values that are ranges (e.g., '1000-1200') into their average, and convert other values to float.
def convertRange(x):
  temp=x.split('-')
  if len(temp) == 2:
    return (float(temp[0]) + float(temp[1]))/2
  try:
    return float(x)
  except:
    return None

In [ ]:
# Apply the 'convertRange' function to the 'total_sqft' column to clean and standardize the values.
data['total_sqft']=data['total_sqft'].apply(convertRange)

In [ ]:
# Display the first few rows of the DataFrame again to see the changes after cleaning 'total_sqft'.
data.head()

                   location       size  total_sqft  bath   price  bhk
0  Electronic City Phase II      2 BHK      1056.0   2.0   39.07    2
1          Chikka Tirupathi  4 Bedroom      2600.0   5.0  120.00    4
2               Uttarahalli      3 BHK      1440.0   2.0   62.00    3
3        Lingadheeranahalli      3 BHK      1521.0   3.0   95.00    3
4                  Kothanur      2 BHK      1200.0   2.0   51.00    2

In [ ]:
# Add a markdown comment to indicate the next step is to calculate 'Price per square feet'.

In [ ]:
# Calculate 'price_per_sqft' by dividing the price (in lakhs, so multiplied by 100000) by 'total_sqft'.
data['price_per_sqft']=data['price']*100000/data['total_sqft']

In [ ]:
# Display the calculated 'price_per_sqft' column.
data['price_per_sqft']

0         3699.810606
1         4615.384615
2         4305.555556
3         6245.890861
4         4250.000000
             ...
13315     6689.834926
13316    11111.111111
13317     5258.545136
13318    10407.336319
13319     3090.909091
Name: price_per_sqft, Length: 13320, dtype: float64

In [ ]:
# Display descriptive statistics for the DataFrame, including the newly created 'price_per_sqft' column.
data.describe()

         total_sqft          bath         price           bhk  price_per_sqft
count  13274.000000  13320.000000  13320.000000  13320.000000    1.327400e+04
mean    1559.626694      2.688814    112.565627      2.802778    7.907501e+03
std     1238.405258      1.338754    148.971674      1.294496    1.064296e+05
min        1.000000      1.000000      8.000000      1.000000    2.678298e+02
25%     1100.000000      2.000000     50.000000      2.000000    4.266865e+03
50%     1276.000000      2.000000     72.000000      3.000000    5.434306e+03
75%     1680.000000      3.000000    120.000000      3.000000    7.311746e+03
max    52272.000000     40.000000   3600.000000     43.000000    1.200000e+07

In [ ]:
# Display the value counts for the 'location' column again to assess its distribution.
data['location'].value_counts()

location
Whitefield                  540
Sarjapur  Road              399
Electronic City             302
Kanakpura Road              273
Thanisandra                 234
                           ...
Mango Garden Layout           1
Milk Colony                   1
Basnashankari,6th stage,      1
Near ullas theater            1
N R Layout                    1
Name: count, Length: 1306, dtype: int64

In [ ]:
# Remove leading/trailing whitespace from 'location' names and then calculate the value counts for each location.
data['location']=data['location'].apply(lambda x: x.strip())
location_count= data['location'].value_counts()

In [ ]:
# Identify locations that appear 10 or fewer times, which will be grouped into 'other'.
location_count_less_10 = location_count[location_count<=10]
location_count_less_10

location
1st Block Koramangala     10
Dairy Circle              10
Nagadevanahalli           10
Sadashiva Nagar           10
Naganathapura             10
                          ..
Xavier Layout              1
Ramanagara Channapatna     1
Maheswari Nagar            1
Hsr layout sector3         1
Thyagraj Nagar             1
Name: count, Length: 1054, dtype: int64

In [ ]:
# Replace infrequent locations (those in 'location_count_less_10') with 'other' to reduce dimensionality.
data['location']=data['location'].apply(lambda x:'other' if x in location_count_less_10 else x)

In [ ]:
# Display the updated value counts for the 'location' column after grouping infrequent locations.
data['location'].value_counts()

location
other                        2886
Whitefield                    541
Sarjapur  Road                399
Electronic City               304
Kanakpura Road                273
                             ...
Tindlu                         11
Marsur                         11
2nd Phase Judicial Layout      11
Thyagaraja Nagar               11
HAL 2nd Stage                  11
Name: count, Length: 242, dtype: int64

In [ ]:
# Add a markdown comment to indicate the next steps involve outlier detection and removal.
#Outliers  Detection and removal

In [ ]:
# Display descriptive statistics for the DataFrame again before outlier removal.
data.describe()

         total_sqft          bath         price           bhk  price_per_sqft
count  13274.000000  13320.000000  13320.000000  13320.000000    1.327400e+04
mean    1559.626694      2.688814    112.565627      2.802778    7.907501e+03
std     1238.405258      1.338754    148.971674      1.294496    1.064296e+05
min        1.000000      1.000000      8.000000      1.000000    2.678298e+02
25%     1100.000000      2.000000     50.000000      2.000000    4.266865e+03
50%     1276.000000      2.000000     72.000000      3.000000    5.434306e+03
75%     1680.000000      3.000000    120.000000      3.000000    7.311746e+03
max    52272.000000     40.000000   3600.000000     43.000000    1.200000e+07

In [ ]:

# Calculate and display descriptive statistics for 'total_sqft' per 'bhk', which is used to identify outliers.
(data['total_sqft']/data['bhk']).describe()

count    13274.000000
mean       575.074878
std        388.205175
min          0.250000
25%        473.333333
50%        552.500000
75%        625.000000
max      26136.000000
dtype: float64

In [ ]:
# Filter out rows where the 'total_sqft' per 'bhk' is less than 300, as these are considered outliers.
data=data[((data['total_sqft']/data['bhk']) >= 300)]
data.describe()

         total_sqft          bath         price           bhk  price_per_sqft
count  12530.000000  12530.000000  12530.000000  12530.000000    12530.000000
mean    1594.564544      2.559537    111.382401      2.650838     6303.979357
std     1261.271296      1.077938    152.077329      0.976678     4162.237981
min      300.000000      1.000000      8.440000      1.000000      267.829813
25%     1116.000000      2.000000     49.000000      2.000000     4210.526316
50%     1300.000000      2.000000     70.000000      3.000000     5294.117647
75%     1700.000000      3.000000    115.000000      3.000000     6916.666667
max    52272.000000     16.000000   3600.000000     16.000000   176470.588235

In [ ]:
# Display the shape of the DataFrame after removing outliers based on 'total_sqft' per 'bhk'.
data.shape

(12530, 7)

In [ ]:
# Display descriptive statistics specifically for the 'price_per_sqft' column.
data.price_per_sqft.describe()

count     12530.000000
mean       6303.979357
std        4162.237981
min         267.829813
25%        4210.526316
50%        5294.117647
75%        6916.666667
max      176470.588235
Name: price_per_sqft, dtype: float64

In [ ]:
# Define a function to remove outliers based on 'price_per_sqft' within each location, using the mean and standard deviation.
def remove_outliers_sqft(df):
  df_output = pd.DataFrame()
  for key,subdf in df.groupby('location'):
    m = np.mean(subdf.price_per_sqft)
    st = np.std(subdf.price_per_sqft)
    gen_df = subdf[(subdf.price_per_sqft > (m-st)) & (subdf.price_per_sqft <= (m+st))]
    df_output = pd.concat([df_output,gen_df],ignore_index = True)
  return df_output
data = remove_outliers_sqft(data)
data.describe()

         total_sqft          bath         price           bhk  price_per_sqft
count  10301.000000  10301.000000  10301.000000  10301.000000    10301.000000
mean    1508.440608      2.471702     91.286372      2.574896     5659.062876
std      880.694214      0.979449     86.342786      0.897649     2265.774749
min      300.000000      1.000000     10.000000      1.000000     1250.000000
25%     1110.000000      2.000000     49.000000      2.000000     4244.897959
50%     1286.000000      2.000000     67.000000      2.000000     5175.600739
75%     1650.000000      3.000000    100.000000      3.000000     6428.571429
max    30400.000000     16.000000   2200.000000     16.000000    24509.803922

In [ ]:
# Define a function to remove BHK outliers. This function iterates through locations and BHK configurations, removing properties where the price per sqft is significantly lower than that of a lower BHK configuration in the same location.
def bhk_outlier_remover(df):
  exclude_indices = np.array([])
  for location, location_df in df.groupby('location'):
    bhk_stats = {}
    for bhk, bhk_df in location_df.groupby('bhk'):
      bhk_stats[bhk] = {
          'mean': np.mean(bhk_df.price_per_sqft),
          'std': np.std(bhk_df.price_per_sqft),
          'count': bhk_df.shape[0]
      }

      for bhk, bhk_df in location_df.groupby('bhk'):
        stats = bhk_stats.get(bhk-1)
        if stats and stats['count']>5:
          exclude_indices = np.append(exclude_indices, bhk_df[bhk_df.price_per_sqft<(stats['mean'])].index.values)
  return df.drop(exclude_indices,axis='index')

In [ ]:
# Apply the 'bhk_outlier_remover' function to the DataFrame to remove BHK-based outliers.
data=bhk_outlier_remover(data)

In [ ]:
# Display the shape of the DataFrame after all outlier removal steps.
data.shape

(7361, 7)

In [ ]:
# Display the entire DataFrame after cleaning and outlier removal.
data

,location,size,total_sqft,bath,price,bhk,price_per_sqft
0,1st Block Jayanagar,4 BHK,2850.0,4.0,428.0,4,15017.543860
1,1st Block Jayanagar,3 BHK,1630.0,3.0,194.0,3,11901.840491
2,1st Block Jayanagar,3 BHK,1875.0,2.0,235.0,3,12533.333333
3,1st Block Jayanagar,3 BHK,1200.0,2.0,130.0,3,10833.333333
4,1st Block Jayanagar,2 BHK,1235.0,2.0,148.0,2,11983.805668
...,...,...,...,...,...,...,...
10292,other,2 BHK,1200.0,2.0,70.0,2,5833.333333
10293,other,1 BHK,1800.0,1.0,200.0,1,11111.111111
10296,other,2 BHK,1353.0,2.0,110.0,2,8130.081301
10297,other,1 Bedroom,812.0,1.0,26.0,1,3201.970443
10300,other,4 BHK,3600.0,5.0,400.0,4,11111.111111

In [ ]:
# Drop the 'size' and 'price_per_sqft' columns as they are no longer needed for model training.
data.drop(columns=['size','price_per_sqft'],inplace=True)

In [ ]:
# Add a markdown comment to indicate that the data is now cleaned.
#Cleaned Data

In [ ]:
# Display the first few rows of the final cleaned DataFrame.
data.head()

              location  total_sqft  bath  price  bhk
0  1st Block Jayanagar      2850.0   4.0  428.0    4
1  1st Block Jayanagar      1630.0   3.0  194.0    3
2  1st Block Jayanagar      1875.0   2.0  235.0    3
3  1st Block Jayanagar      1200.0   2.0  130.0    3
4  1st Block Jayanagar      1235.0   2.0  148.0    2

In [ ]:
# Save the cleaned DataFrame to a new CSV file named 'Cleaned_data.csv'.
data.to_csv("Cleaned_data.csv")

In [ ]:
# Separate the features (X) from the target variable (y, which is 'price').
X=data.drop(columns=['price'])
y=data['price']

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression,Lasso,Ridge
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.compose import make_column_transformer
from sklearn.pipeline import make_pipeline
from sklearn.metrics import r2_score

In [ ]:
# Split the data into training and testing sets (80% training, 20% testing) for model evaluation.
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=0)

In [ ]:
# Print the shapes of the training and testing feature sets to verify the split.
print(X_train.shape)
print(X_test.shape)

(5888, 4)
(1473, 4)

In [ ]:
# Add a markdown comment to indicate the application of Linear Regression.
#Applying Linear Regression

In [ ]:
# Create a ColumnTransformer to apply OneHotEncoder to the 'location' column, and leave other columns as is.
column_trans = make_column_transformer((OneHotEncoder(sparse_output=False),['location']),remainder='passthrough')

In [ ]:
# Initialize a StandardScaler to scale numerical features.
scaler = StandardScaler()

In [ ]:
# Empty cell, could be used for additional setup or comments.

In [ ]:
# Empty cell, could be used for additional setup or comments.

In [ ]:
# Initialize a Linear Regression model.
lr = LinearRegression()

In [ ]:
# Create a pipeline that first applies the column transformations (OneHotEncoder), then scales the data, and finally applies Linear Regression.
pipe = make_pipeline(column_trans,scaler,lr)

In [ ]:
# Fit the Linear Regression pipeline to the training data.
pipe.fit(X_train,y_train)

/usr/local/lib/python3.12/dist-packages/sklearn/compose/_column_transformer.py:1667: FutureWarning:
The format of the columns of the 'remainder' transformer in ColumnTransformer.transformers_ will change in version 1.7 to match the format of the other transformers.
At the moment the remainder columns are stored as indices (of type int). With the same ColumnTransformer configuration, in the future they will be stored as column names (of type str).
To use the new behavior now and suppress this warning, use ColumnTransformer(force_int_remainder_cols=False).

  warnings.warn(

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('onehotencoder',
                                                  OneHotEncoder(sparse_output=False),
                                                  ['location'])])),
                ('standardscaler', StandardScaler()),
                ('linearregression', LinearRegression())])

In [ ]:
# Use the trained Linear Regression pipeline to make predictions on the test set.
y_pred_lr = pipe.predict(X_test)

In [ ]:
# Calculate and display the R-squared score for the Linear Regression model, comparing actual vs. predicted values.
r2_score(y_test,y_pred_lr)

0.8233783132019381

In [ ]:
# Add a markdown comment to indicate the next step is to apply Lasso Regression.
# Applying Lasso

In [ ]:
# Initialize a Lasso Regression model.
lasso = Lasso()

In [ ]:
# Create a new pipeline for Lasso Regression, incorporating column transformations, scaling, and the Lasso model.
pipe = make_pipeline(column_trans,scaler,lasso)

In [ ]:
# Fit the Lasso Regression pipeline to the training data.
pipe.fit(X_train,y_train)

/usr/local/lib/python3.12/dist-packages/sklearn/compose/_column_transformer.py:1667: FutureWarning:
The format of the columns of the 'remainder' transformer in ColumnTransformer.transformers_ will change in version 1.7 to match the format of the other transformers.
At the moment the remainder columns are stored as indices (of type int). With the same ColumnTransformer configuration, in the future they will be stored as column names (of type str).
To use the new behavior now and suppress this warning, use ColumnTransformer(force_int_remainder_cols=False).

  warnings.warn(

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('onehotencoder',
                                                  OneHotEncoder(sparse_output=False),
                                                  ['location'])])),
                ('standardscaler', StandardScaler()), ('lasso', Lasso())])

In [ ]:
# Use the trained Lasso Regression pipeline to make predictions on the test set and calculate its R-squared score.
y_pred_lasso = pipe.predict(X_test)
r2_score(y_test,y_pred_lasso)

0.8128285650772719

In [ ]:
# Add a markdown comment to indicate the next step is to apply Ridge Regression.
# Applying Ridge

In [ ]:
# Initialize a Ridge Regression model.
ridge = Ridge()

In [ ]:
pipe = make_pipeline(column_trans,scaler,ridge)

In [ ]:
pipe.fit(X_train,y_train)

/usr/local/lib/python3.12/dist-packages/sklearn/compose/_column_transformer.py:1667: FutureWarning:
The format of the columns of the 'remainder' transformer in ColumnTransformer.transformers_ will change in version 1.7 to match the format of the other transformers.
At the moment the remainder columns are stored as indices (of type int). With the same ColumnTransformer configuration, in the future they will be stored as column names (of type str).
To use the new behavior now and suppress this warning, use ColumnTransformer(force_int_remainder_cols=False).

  warnings.warn(

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('onehotencoder',
                                                  OneHotEncoder(sparse_output=False),
                                                  ['location'])])),
                ('standardscaler', StandardScaler()), ('ridge', Ridge())])

In [ ]:
# Use the trained Ridge Regression pipeline to make predictions on the test set and calculate its R-squared score.
y_pred_ridge = pipe.predict(X_test)
r2_score(y_test,y_pred_ridge)

0.8234146633312639

In [ ]:
# Print and compare the R-squared scores for all three models: Linear Regression (No Regularization), Lasso, and Ridge.
print("No Regularization: ", r2_score(y_test,y_pred_lr))
print("Lasso: ", r2_score(y_test,y_pred_lasso))
print("Ridge: ", r2_score(y_test,y_pred_ridge))

No Regularization:  0.8233783132019381
Lasso:  0.8128285650772719
Ridge:  0.8234146633312639

In [ ]:
# Import the pickle library, which is used for serializing and de-serializing Python objects.
import pickle

In [ ]:
# Save the trained Ridge Regression pipeline to a file named 'RidgeModel.pkl' for future use.
pickle.dump(pipe,open('RidgeModel.pkl','wb'))

In [ ]:
# Empty cell, could be used for additional setup or comments.

In [ ]:
import joblib

# Save the trained Ridge Regression pipeline
joblib.dump(pipe, "RidgeModel_new.joblib")
print("Saved successfully!")

Saved successfully!

In [ ]:
# Re-defining and saving the Ridge Regression pipeline correctly

from sklearn.compose import make_column_transformer
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.linear_model import Ridge
from sklearn.pipeline import make_pipeline
import joblib

# 1. Define column_trans (OneHotEncoder for 'location')
column_trans = make_column_transformer((OneHotEncoder(sparse_output=False),['location']),remainder='passthrough')

# 2. Initialize scaler
scaler = StandardScaler()

# 3. Initialize Ridge model
ridge = Ridge()

# 4. Create the pipeline
pipe = make_pipeline(column_trans,scaler,ridge)

# 5. Fit the pipeline to the training data
pipe.fit(X_train,y_train)

# 6. Save the trained Ridge Regression pipeline
joblib.dump(pipe, "RidgeModel_new.joblib")
print("RidgeModel_new.joblib saved successfully!")

RidgeModel_new.joblib saved successfully!

### Streamlit Application for House Price Prediction

Streamlit is an open-source Python library that makes it easy to create and share beautiful, custom web apps for machine learning and data science. In this project, you can use Streamlit to build an interactive interface where users can input details about a house and get a predicted price based on your trained Ridge Regression model.

To run a Streamlit app, you would typically save the following code in a `.py` file (e.g., `app.py`) and then execute it from your terminal using `streamlit run app.py`.

In [ ]:
%%writefile bengaluru-house-price-predictor/app.py
import streamlit as st
import joblib
import pandas as pd

# Load the trained model
try:
    model = joblib.load('bengaluru-house-price-predictor/model.pkl')
except FileNotFoundError:
    st.error("Model file 'bengaluru-house-price-predictor/model.pkl' not found. Please ensure it has been saved correctly.")
    st.stop()

st.title('Bengaluru House Price Prediction')

# Input fields for features
st.header('Enter House Details')

location = st.selectbox('Location', ['other', 'Whitefield', 'Sarjapur  Road', 'Electronic City', 'Kanakpura Road', 'Thanisandra', 'Yelahanka', 'Uttarahalli', 'Hebbal', 'Raja Rajeshwari Nagar', 'Marathahalli', 'Hennur Road', 'Banashankari', 'Haralur Road', 'Electronic City Phase II', 'Hosur Road', 'Old Airport Road', 'Kothanur', 'Rustam Bagh', 'Kadugodi', '7th Phase JP Nagar', 'Kaggadasapura', 'Chandapura', 'Kengeri', 'Domlur', 'Yeshwanthpur', 'Sarjapur', 'Kasavanhalli', 'Begur Road', 'Ramamurthy Nagar', 'Malleshwaram', 'Varthur', 'Bommasandra', 'BTM 2nd Stage', 'Tin Factory', 'Bellandur', 'Panathur', 'JP Nagar', 'Cunningham Road', 'HSR Layout', 'Devanahalli', 'Gottigere', 'Mysore Road', 'KR Puram', 'Frazer Town', 'Anekal', 'Jigani', 'Attibele', 'Lakshminarayana Pura', 'Hoodi', 'Koramangala', 'Hosa Road', 'Kudlu Gate', 'Akshaya Nagar', 'Binny Pete', 'Thigalarapalya', 'Talaghattapura', 'Vidyaranyapura', 'Subramanyapura', 'Old Madras Road', 'Bommanahalli', 'Balagere', 'Kenchenahalli', 'Green Glen Layout', 'EPIP Zone', 'Rajaji Nagar', 'Kodichikkanahalli', 'Kaval Byrasandra', 'Konanakunte', 'Kothannur', 'TC Palaya', 'Kasturi Nagar', 'Ambalipura', 'Manyata Tech Park', 'Bhoganhalli', 'Yelahanka New Town', 'Jalahalli', 'Magadi Road', 'Singasandra', 'Budigere', 'Kengeri Satellite Town', 'Brookefield', 'Bannerghatta Road', 'Kaikondrahalli', 'Harlur', 'Hulimavu', 'Hoskote', 'HBR Layout', 'Doddathoguru', 'Somasundara Palya', 'Kumbalgodu', 'Horamavu Agara', 'Nagavara', 'Horamavu', 'Whitefield,', 'Ambedkar Nagar', 'Battarahalli', 'Kannamangala', 'Tumkur Road', 'Kengeri Hobli', 'Dodda Nekkundi', 'Ardendale', 'Channasandra', 'Vasanthapura', 'Benson Town', 'Hegde Nagar', 'Thurahalli', 'Varthur Road', 'Kathriguppe', 'Halanayakanahalli', 'Hegganahalli', 'Gunjur', 'Singena Agrahara', 'Electronic City Phase I', 'Yelahanka, Jakkur', 'Byatarayanapura', 'Margondanahalli', 'Arekere', 'Seegehalli', 'Kanakapura', 'Dasanapura', 'Kengeri Main Road', 'Ramakrishnappa Layout', 'Bisuvanahalli', 'Jakkur', 'Kundalahalli', 'Bikasipura', 'Sahakara Nagar', 'Rayasandra', 'Kodigehalli', 'Begur', 'Banashankari Stage III', 'Choodasandra', 'Hadosiddapura', 'JP Nagar, Phase 1', 'Subramanya Pura', 'Jalahalli West', 'Doddenakundi Industrial Estate', 'Jayamahal', 'Gollahalli', 'Carmelaram', 'Kudlu', 'K Narayanapura', 'Borewell Road', 'Kanakapura Road,', 'Chikkalasandra', 'Talakaveri Layout', 'Jakkur Plantation', 'Chikkabanavar', 'Hoodi Residential Locality', 'Kothanur,', 'Kodihalli', 'Vittasandra', 'HSR Layout Sector 2', 'Nagasandra', 'Varthur, Whitefield', 'Kalyan Nagar', 'Balagere Road', 'Chikkaballapur', 'Hongasandra', 'Kogilu', 'Old Town', 'Gubbalala', 'Pattandur Agrahara', 'BTM Layout', 'Koramangala,', 'Nallurhalli', 'Konappana Agrahara', 'Panathur Road', 'Banashankari Stage II', 'Dodsworth Layout', 'ITPL', 'Anjanapura', 'Varanasi', 'Kannahalli', 'Hennur Bande', 'Abbigere', 'Sarjapur Road,', 'Sompura', 'Kengeri Satellite Town,', 'Rachenahalli', 'Banashankari Stage VI', 'Harlur Road', 'Ananth Nagar', 'R.T. Nagar', 'Hulimavu,', 'CV Raman Nagar', 'Tindlu', 'Marsur', '2nd Phase Judicial Layout', 'Thyagaraja Nagar', 'HAL 2nd Stage'])
total_sqft = st.number_input('Total Square Feet', min_value=300.0, max_value=50000.0, value=1200.0)
bath = st.slider('Number of Bathrooms', min_value=1, max_value=16, value=2)
bhk = st.slider('Number of BHK', min_value=1, max_value=16, value=2)

if st.button('Predict Price'):
    # Create a DataFrame for prediction
    input_data = pd.DataFrame([{
        'location': location,
        'total_sqft': total_sqft,
        'bath': float(bath),
        'bhk': float(bhk)
    }])

    # Make prediction
    prediction = model.predict(input_data)[0]
    st.success(f'Predicted House Price: ₹ {prediction:.2f} Lakhs')

Writing bengaluru-house-price-predictor/app.py

In [ ]:
!pip install streamlit

import streamlit as st
import joblib
import pandas as pd

# Load the trained model
# Assuming 'RidgeModel_new.joblib' was successfully saved from the pipeline object
# You might need to re-run the cell where the 'pipe' was defined and saved if it wasn't successful.
try:
    model = joblib.load('RidgeModel_new.joblib')
except FileNotFoundError:
    st.error("Model file 'RidgeModel_new.joblib' not found. Please ensure it has been saved correctly.")
    st.stop()

st.title('Bengaluru House Price Prediction')

# Input fields for features
st.header('Enter House Details')

location = st.selectbox('Location', ['other', 'Whitefield', 'Sarjapur  Road', 'Electronic City', 'Kanakpura Road', 'Thanisandra', 'Yelahanka', 'Uttarahalli', 'Hebbal', 'Raja Rajeshwari Nagar', 'Marathahalli', 'Hennur Road', 'Banashankari', 'Haralur Road', 'Electronic City Phase II', 'Hosur Road', 'Old Airport Road', 'Kothanur', 'Rustam Bagh', 'Kadugodi', '7th Phase JP Nagar', 'Kaggadasapura', 'Chandapura', 'Kengeri', 'Domlur', 'Yeshwanthpur', 'Sarjapur', 'Kasavanhalli', 'Begur Road', 'Ramamurthy Nagar', 'Malleshwaram', 'Varthur', 'Bommasandra', 'BTM 2nd Stage', 'Tin Factory', 'Bellandur', 'Panathur', 'JP Nagar', 'Cunningham Road', 'HSR Layout', 'Devanahalli', 'Gottigere', 'Mysore Road', 'KR Puram', 'Frazer Town', 'Anekal', 'Jigani', 'Attibele', 'Lakshminarayana Pura', 'Hoodi', 'Koramangala', 'Hosa Road', 'Kudlu Gate', 'Akshaya Nagar', 'Binny Pete', 'Thigalarapalya', 'Talaghattapura', 'Vidyaranyapura', 'Subramanyapura', 'Old Madras Road', 'Bommanahalli', 'Balagere', 'Kenchenahalli', 'Green Glen Layout', 'EPIP Zone', 'Rajaji Nagar', 'Kodichikkanahalli', 'Kaval Byrasandra', 'Konanakunte', 'Kothannur', 'TC Palaya', 'Kasturi Nagar', 'Ambalipura', 'Manyata Tech Park', 'Bhoganhalli', 'Yelahanka New Town', 'Jalahalli', 'Magadi Road', 'Singasandra', 'Budigere', 'Kengeri Satellite Town', 'Brookefield', 'Bannerghatta Road', 'Kaikondrahalli', 'Harlur', 'Hulimavu', 'Hoskote', 'HBR Layout', 'Doddathoguru', 'Somasundara Palya', 'Kumbalgodu', 'Horamavu Agara', 'Nagavara', 'Horamavu', 'Whitefield,', 'Ambedkar Nagar', 'Battarahalli', 'Kannamangala', 'Tumkur Road', 'Kengeri Hobli', 'Dodda Nekkundi', 'Ardendale', 'Channasandra', 'Vasanthapura', 'Benson Town', 'Hegde Nagar', 'Thurahalli', 'Varthur Road', 'Kathriguppe', 'Halanayakanahalli', 'Hegganahalli', 'Gunjur', 'Singena Agrahara', 'Electronic City Phase I', 'Yelahanka, Jakkur', 'Byatarayanapura', 'Margondanahalli', 'Arekere', 'Seegehalli', 'Kanakapura', 'Dasanapura', 'Kengeri Main Road', 'Ramakrishnappa Layout', 'Bisuvanahalli', 'Jakkur', 'Kundalahalli', 'Bikasipura', 'Sahakara Nagar', 'Rayasandra', 'Kodigehalli', 'Begur', 'Banashankari Stage III', 'Choodasandra', 'Hadosiddapura', 'JP Nagar, Phase 1', 'Subramanya Pura', 'Jalahalli West', 'Doddenakundi Industrial Estate', 'Jayamahal', 'Gollahalli', 'Carmelaram', 'Kudlu', 'K Narayanapura', 'Borewell Road', 'Kanakapura Road,', 'Chikkalasandra', 'Talakaveri Layout', 'Jakkur Plantation', 'Chikkabanavar', 'Hoodi Residential Locality', 'Kothanur,', 'Kodihalli', 'Vittasandra', 'HSR Layout Sector 2', 'Nagasandra', 'Varthur, Whitefield', 'Kalyan Nagar', 'Balagere Road', 'Chikkaballapur', 'Hongasandra', 'Kogilu', 'Old Town', 'Gubbalala', 'Pattandur Agrahara', 'BTM Layout', 'Koramangala,', 'Nallurhalli', 'Konappana Agrahara', 'Panathur Road', 'Banashankari Stage II', 'Dodsworth Layout', 'ITPL', 'Anjanapura', 'Varanasi', 'Kannahalli', 'Hennur Bande', 'Abbigere', 'Sarjapur Road,', 'Sompura', 'Kengeri Satellite Town,', 'Rachenahalli', 'Banashankari Stage VI', 'Harlur Road', 'Ananth Nagar', 'R.T. Nagar', 'Hulimavu,', 'CV Raman Nagar', 'Tindlu', 'Marsur', '2nd Phase Judicial Layout', 'Thyagaraja Nagar', 'HAL 2nd Stage'])
total_sqft = st.number_input('Total Square Feet', min_value=300.0, max_value=50000.0, value=1200.0)
bath = st.slider('Number of Bathrooms', min_value=1, max_value=16, value=2)
bhk = st.slider('Number of BHK', min_value=1, max_value=16, value=2)

if st.button('Predict Price'):
    # Create a DataFrame for prediction
    input_data = pd.DataFrame([{
        'location': location,
        'total_sqft': total_sqft,
        'bath': float(bath),
        'bhk': float(bhk)
    }])

    # Make prediction
    prediction = model.predict(input_data)[0]
    st.success(f'Predicted House Price: ₹ {prediction:.2f} Lakhs')

# To run this Streamlit app:
# 1. Save the code above to a file named `app.py`.
# 2. Open your terminal or command prompt.
# 3. Navigate to the directory where you saved `app.py`.
# 4. Run the command: `streamlit run app.py`
# 5. Your web browser will open with the Streamlit application.

Requirement already satisfied: streamlit in /usr/local/lib/python3.12/dist-packages (1.58.0)
Requirement already satisfied: altair!=5.4.0,!=5.4.1,<7,>=4.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (5.5.0)
Requirement already satisfied: blinker<2,>=1.5.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (1.9.0)
Requirement already satisfied: cachetools<8,>=5.5 in /usr/local/lib/python3.12/dist-packages (from streamlit) (6.2.6)
Requirement already satisfied: click<9,>=7.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (8.4.1)
Requirement already satisfied: gitpython!=3.1.19,<4,>=3.0.7 in /usr/local/lib/python3.12/dist-packages (from streamlit) (3.1.50)
Requirement already satisfied: numpy<3,>=1.23 in /usr/local/lib/python3.12/dist-packages (from streamlit) (2.0.2)
Requirement already satisfied: packaging>=20 in /usr/local/lib/python3.12/dist-packages (from streamlit) (26.2)
Requirement already satisfied: pandas<4,>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (2.2.2)
Requirement already satisfied: pillow<13,>=7.1.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (11.3.0)
Requirement already satisfied: pydeck<1,>=0.8.0b4 in /usr/local/lib/python3.12/dist-packages (from streamlit) (0.9.2)
Requirement already satisfied: protobuf<8,>=3.20 in /usr/local/lib/python3.12/dist-packages (from streamlit) (5.29.6)
Requirement already satisfied: pyarrow>=7.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (18.1.0)
Requirement already satisfied: requests<3,>=2.27 in /usr/local/lib/python3.12/dist-packages (from streamlit) (2.32.4)
Requirement already satisfied: tenacity<10,>=8.1.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (9.1.4)
Requirement already satisfied: toml<2,>=0.10.1 in /usr/local/lib/python3.12/dist-packages (from streamlit) (0.10.2)
Requirement already satisfied: typing-extensions<5,>=4.10.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (4.15.0)
Requirement already satisfied: starlette>=0.40.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (0.52.1)
Requirement already satisfied: uvicorn>=0.30.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (0.49.0)
Requirement already satisfied: httptools>=0.6.3 in /usr/local/lib/python3.12/dist-packages (from streamlit) (0.8.0)
Requirement already satisfied: anyio>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (4.13.0)
Requirement already satisfied: python-multipart>=0.0.10 in /usr/local/lib/python3.12/dist-packages (from streamlit) (0.0.32)
Requirement already satisfied: websockets>=12.0.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (15.0.1)
Requirement already satisfied: itsdangerous>=2.1.2 in /usr/local/lib/python3.12/dist-packages (from streamlit) (2.2.0)
Requirement already satisfied: watchdog<7,>=2.1.5 in /usr/local/lib/python3.12/dist-packages (from streamlit) (6.0.0)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (3.1.6)
Requirement already satisfied: jsonschema>=3.0 in /usr/local/lib/python3.12/dist-packages (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (4.26.0)
Requirement already satisfied: narwhals>=1.14.2 in /usr/local/lib/python3.12/dist-packages (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (2.22.1)
Requirement already satisfied: idna>=2.8 in /usr/local/lib/python3.12/dist-packages (from anyio>=4.0.0->streamlit) (3.18)
Requirement already satisfied: gitdb<5,>=4.0.1 in /usr/local/lib/python3.12/dist-packages (from gitpython!=3.1.19,<4,>=3.0.7->streamlit) (4.0.12)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas<4,>=1.4.0->streamlit) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas<4,>=1.4.0->streamlit) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas<4,>=1.4.0->streamlit) (2026.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.27->streamlit) (3.4.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.27->streamlit) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.27->streamlit) (2026.5.20)
Requirement already satisfied: h11>=0.8 in /usr/local/lib/python3.12/dist-packages (from uvicorn>=0.30.0->streamlit) (0.16.0)
Requirement already satisfied: smmap<6,>=3.0.1 in /usr/local/lib/python3.12/dist-packages (from gitdb<5,>=4.0.1->gitpython!=3.1.19,<4,>=3.0.7->streamlit) (5.0.3)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (3.0.3)
Requirement already satisfied: attrs>=22.2.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (26.1.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (2026.5.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas<4,>=1.4.0->streamlit) (1.17.0)

2026-06-17 13:06:24.116 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-17 13:06:24.117 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-17 13:06:24.118 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-17 13:06:24.119 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-17 13:06:24.120 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-17 13:06:24.121 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-17 13:06:24.122 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-17 13:06:24.124 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-17 13:06:24.125 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-17 13:06:24.126 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-17 13:06:24.127 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-17 13:06:24.128 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-17 13:06:24.128 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-17 13:06:24.130 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-17 13:06:24.131 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-17 13:06:24.132 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-17 13:06:24.133 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-17 13:06:24.134 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-17 13:06:24.135 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-17 13:06:24.135 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-17 13:06:24.136 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-17 13:06:24.138 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-17 13:06:24.138 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-17 13:06:24.139 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-17 13:06:24.141 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-17 13:06:24.141 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-17 13:06:24.142 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-17 13:06:24.146 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-17 13:06:24.147 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-17 13:06:24.148 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-17 13:06:24.149 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-17 13:06:24.150 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-17 13:06:24.151 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-17 13:06:24.153 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-17 13:06:24.153 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-17 13:06:24.154 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-17 13:06:24.156 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-17 13:06:24.156 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.

In [ ]:
!pip install streamlit pyngrok joblib scikit-learn pandas numpy

Requirement already satisfied: streamlit in /usr/local/lib/python3.12/dist-packages (1.58.0)
Requirement already satisfied: pyngrok in /usr/local/lib/python3.12/dist-packages (8.1.2)
Requirement already satisfied: joblib in /usr/local/lib/python3.12/dist-packages (1.5.3)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.12/dist-packages (1.6.1)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (2.0.2)
Requirement already satisfied: altair!=5.4.0,!=5.4.1,<7,>=4.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (5.5.0)
Requirement already satisfied: blinker<2,>=1.5.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (1.9.0)
Requirement already satisfied: cachetools<8,>=5.5 in /usr/local/lib/python3.12/dist-packages (from streamlit) (6.2.6)
Requirement already satisfied: click<9,>=7.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (8.4.1)
Requirement already satisfied: gitpython!=3.1.19,<4,>=3.0.7 in /usr/local/lib/python3.12/dist-packages (from streamlit) (3.1.50)
Requirement already satisfied: packaging>=20 in /usr/local/lib/python3.12/dist-packages (from streamlit) (26.2)
Requirement already satisfied: pillow<13,>=7.1.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (11.3.0)
Requirement already satisfied: pydeck<1,>=0.8.0b4 in /usr/local/lib/python3.12/dist-packages (from streamlit) (0.9.2)
Requirement already satisfied: protobuf<8,>=3.20 in /usr/local/lib/python3.12/dist-packages (from streamlit) (5.29.6)
Requirement already satisfied: pyarrow>=7.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (18.1.0)
Requirement already satisfied: requests<3,>=2.27 in /usr/local/lib/python3.12/dist-packages (from streamlit) (2.32.4)
Requirement already satisfied: tenacity<10,>=8.1.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (9.1.4)
Requirement already satisfied: toml<2,>=0.10.1 in /usr/local/lib/python3.12/dist-packages (from streamlit) (0.10.2)
Requirement already satisfied: typing-extensions<5,>=4.10.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (4.15.0)
Requirement already satisfied: starlette>=0.40.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (0.52.1)
Requirement already satisfied: uvicorn>=0.30.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (0.49.0)
Requirement already satisfied: httptools>=0.6.3 in /usr/local/lib/python3.12/dist-packages (from streamlit) (0.8.0)
Requirement already satisfied: anyio>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (4.13.0)
Requirement already satisfied: python-multipart>=0.0.10 in /usr/local/lib/python3.12/dist-packages (from streamlit) (0.0.32)
Requirement already satisfied: websockets>=12.0.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (15.0.1)
Requirement already satisfied: itsdangerous>=2.1.2 in /usr/local/lib/python3.12/dist-packages (from streamlit) (2.2.0)
Requirement already satisfied: watchdog<7,>=2.1.5 in /usr/local/lib/python3.12/dist-packages (from streamlit) (6.0.0)
Requirement already satisfied: PyYAML>=5.1 in /usr/local/lib/python3.12/dist-packages (from pyngrok) (6.0.3)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (1.16.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.2)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (3.1.6)
Requirement already satisfied: jsonschema>=3.0 in /usr/local/lib/python3.12/dist-packages (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (4.26.0)
Requirement already satisfied: narwhals>=1.14.2 in /usr/local/lib/python3.12/dist-packages (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (2.22.1)
Requirement already satisfied: idna>=2.8 in /usr/local/lib/python3.12/dist-packages (from anyio>=4.0.0->streamlit) (3.18)
Requirement already satisfied: gitdb<5,>=4.0.1 in /usr/local/lib/python3.12/dist-packages (from gitpython!=3.1.19,<4,>=3.0.7->streamlit) (4.0.12)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.27->streamlit) (3.4.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.27->streamlit) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.27->streamlit) (2026.5.20)
Requirement already satisfied: h11>=0.8 in /usr/local/lib/python3.12/dist-packages (from uvicorn>=0.30.0->streamlit) (0.16.0)
Requirement already satisfied: smmap<6,>=3.0.1 in /usr/local/lib/python3.12/dist-packages (from gitdb<5,>=4.0.1->gitpython!=3.1.19,<4,>=3.0.7->streamlit) (5.0.3)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (3.0.3)
Requirement already satisfied: attrs>=22.2.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (26.1.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (2026.5.1)

In [ ]:
!streamlit run app.py &>/content/logs.txt &

In [ ]:
from pyngrok import ngrok

# Replace 'YOUR_AUTHTOKEN' with your actual ngrok authtoken
# You can get your authtoken from https://dashboard.ngrok.com/get-started/your-authtoken
ngrok.set_auth_token('3FGU25aGBouONGpxd3C8KRU2eHB_4nUeEiJznzM1aKrgbkfBP')

public_url = ngrok.connect(8502)
print(public_url)

NgrokTunnel: "https://throbbing-harbor-dazzler.ngrok-free.dev" -> "http://localhost:8502"

In [ ]:
# Create the directory for the project structure
!mkdir -p bengaluru-house-price-predictor

In [ ]:
# Move and rename the trained model file to the new directory
!mv RidgeModel_new.joblib bengaluru-house-price-predictor/model.pkl
print("RidgeModel_new.joblib moved and renamed to bengaluru-house-price-predictor/model.pkl")

RidgeModel_new.joblib moved and renamed to bengaluru-house-price-predictor/model.pkl

In [ ]:
import joblib

# Replace 'ridge_model' with the exact variable name of your trained model
joblib.dump(pipe, 'RidgeModel_new.joblib')

['RidgeModel_new.joblib']

In [ ]:
!python -c "import sklearn; print(sklearn.__version__)"

1.6.1

NgrokTunnel: "https://throbbing-harbor-dazzler.ngrok-free.dev" -> "http://localhost:8501"